spring:
  datasource:
    username: root
    password: Ventana1204
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "resanelisoa@gmail.com"
    password: "Ventana1204"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configuración personalizada para el proyecto
project:
  poster: poster/

# Base URL de la aplicación
base:
  url: "http://localhost:8080"
